### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by somemildviolins** [adafruit/Adafruit-Retrogame#10]
I have downloaded "Adafruit-Retrogame" (and later, i downloaded "Adafruit-Retrogame.master").  I did this from within the Raspberry Pi after typing "startx" and the using one of the browsers.  Once downloaded, it creates a zip folder on the desktop.   Then, by clicking on it i can get the files unzipped.  They show up in a folder together.

Then i log out and go to the command prompt.  I type "cd Adafruit-Retrogame" and it says that the file is not found.  Thats where I'm stuck.

Ive gotten further along than this before, but this time i cant get past this.

**Comment by langmeister** [comment]
This is probably more a general RPI/Linux issue, but in case you didn't already solve this...

Based on the premise that the folder is on your desktop you likely need to cd to "~/Desktop/Adafruit-Retrogame" from a new terminal prompt.

sudo ~/Desktop/Adafruit-Retrogame/retrogame &

HTH

**Comment by somemildviolins** [comment]
Thank you very much.  I figured this out with some trial and error.   I actually solved it a little differently than you suggested by just moving the folder off of the desktop and into the correct folder where applications are supposed to be (I cannot recall from memory where that is, but I know now it is NOT the desktop... haha).   By doing this, then I could just follow the awesome instructions you guys posted on Adafruit.     Here is a link to the arcade we built.   http://www.adafruit.com/blog/2015/01/09/donkey-kong-bartop-arcade-powered-by-rpi-raspberry_pi-piday-raspberrypi/

**Comment by somemildviolins** [comment]
If someone ever wanted to do so or felt it was necessary (I may be the only one to ever have a problem like this), I would suggest a sentence in the beginning of the Retrogame instructions that told people where to put the files on the Pi, since the later in the instructions they assume a specific location where it will be found.   No big deal, though.   It might also be assuming that I know something about Linux, haha, which I didn't then but I know enough to be dangerous now.

**Comment by somemildviolins** [comment]
Here it is:   /home/pi.    Once the Adafruit-Retrogame folder was moved to the /home/pi directory, it worked.
