### ISSUE TITLE
Optical Switch Issues

### ISSUE THREAD

**Issue by simon96aic** [adafruit/Adafruit-Retrogame#23]
root@retropie:/home/pi# cat /sys/class/gpio/gpio21/value
0

-> retrogame simulate endless key input.

When i hold something into this optical switch:
root@retropie:/home/pi# cat /sys/class/gpio/gpio21/value
1

-> No key input

retrogame simulate by the false gpio state

Or is the problem with me?

**Comment by ladyada** [comment]
as long as the device gives high/low voltage to the pin, it'll work - so probably a hardware/sensor issue
