### ISSUE TITLE
Retropie 4.0.2 not working with latest Retrogame (WIP)

### ISSUE THREAD

**Issue by RzvnB** [adafruit/Adafruit-Retrogame#30]
The latest retrogame is not working with the latest Retropie. I'd suggest that you make the WIP (config files feature) a different branch, and make the 11 august version the master branch (that one works).

**Comment by PaintYourDragon** [comment]
#ifdef'd the WIP stuff for the time being, download latest and all is good. Sorry about that, didn't mean to break things. Very close to being done! Thanks for the heads-up.
