### ISSUE TITLE
Another question? Does the software support an 8 way Joystick?

### ISSUE THREAD

**Issue by washplant26** [adafruit/Adafruit-Retrogame#34]
My question is if I was playing could I do diagonal so not just Left, Right, Up, and down, could it be up-left, upright, down-right, down,left? Thanks again for taking the time to look at the questions and issues. :)

**Comment by PaintYourDragon** [comment]
Yes. In fact this is how "8 way" joysticks typically work internally -- activating two cardinal directions simultaneously. The code supports this.
