### ISSUE TITLE
I have followed the intructions

### ISSUE THREAD

**Issue by washplant26** [adafruit/Adafruit-Retrogame#36]
I followed the instructions I have hooked up my arcade button to the correct two pins the ground and pin 5 I have not changed the config file but have moved it to the boot folder as it recommended. I just want to try to do a simple space in a text editor just to see if the code works properly. My end goal is to make an arcade cabinet. Please help with any advice or things to do to make this great idea work. Thank you :)

**Comment by PaintYourDragon** [comment]
Confirm retrogame is running in the background ('ps' command, etc.). Confirm button is connected to GPIO5, which isn't the same location as "physical" pin 5 along the header.
Code's tested and known working on current RetroPie and Raspbian on various models of Pi. Make sure no steps were skipped. Confirm that button in fact works, using a multimeter or LED or something to test continuity.
