### ISSUE TITLE
Multiplayer keybinding.

### ISSUE THREAD

**Issue by Plevoscoba** [adafruit/Adafruit-Retrogame#39]
Hi!

Can't find it neither on the Adafruit's forum nor here so I ask: How can I make retrogame work for two players?

When configuring my buttons connected to the GPIO they are known as "Keyboard" and I can only configure one set of command but I'd like to enjoy multi-players games so I need it to bind two sets of commands.

Many thanks in advance!

**Comment by PaintYourDragon** [comment]
Please try the RetroPie Forum at https://retropie.org.uk/forum/
I suspect there's a global retroarch.cfg file that'll need editing to assign certain key presses to "player 1" or "player 2". But I don't really know RetroPie inside and out. Folks in the forum there should have a better handle on it.

retrogame just assigns GPIO inputs to virtual key presses. That's the end of it; no "context" as to which player or function said keypress relates to. That's an emulator config issue.
