### ISSUE TITLE
All pins pulled high

### ISSUE THREAD

**Issue by simondid** [adafruit/Adafruit-Retrogame#44]
hey

so i'm traying to set this up to run with retro pi my problem is that i have a some electronics on gpio 1 witch if pulled high turns off my screen and if low turns on the screen 

what i need is a way to make you're script to do nothing to gpio 1 preferably a setting in the settings file witch allows me to edit this

**Comment by PaintYourDragon** [comment]
retrogame doesn't modify any pins which aren't explicitly mentioned in the settings file (/boot/retrogame.cfg). If it's not mentioned in there, it's not doing pullups.

'GPIO1' is presumably a WiringPi pin number. retrogame uses Broadcom pin numbers, so look for anything mentioning GPIO18 (corresponds to WiringPi's pin 1) and change it. Shouldn't need to reboot; takes effect when changes are written to config file.

If that's not it, maybe something else it acting on that pin (e.g. some PWM audio hacks).
