### ISSUE TITLE
Retrogame virtual keyboard Kodi 17.3 not recognized

### ISSUE THREAD

**Issue by AssoMania** [adafruit/Adafruit-Retrogame#45]
Hello there,

I encounter a problem regarding the buttons in Kodi. The buttons aren't working even tho' it's working on the "desktop" and retropie.

I put a Pi Zero W into a PSP. Connected the GPIO to the controls of the PSP. I then installed a Raspbian Image. I apt-get install kodi to get kodi. And also installed Retropie manually using this [link](https://github.com/retropie/retropie-setup/wiki/manual-installation).
I use retrogame.cfg file to make the buttons work. And copy the retrogame in /usr/local/bin/retrogame (both files has been given to me so I don't really know thing about them, sorry).

```
# Sample configuration file for retrogame.
# Really minimal syntax, typically two elements per line w/space delimiter:
# 1) a key name (from keyTable.h; shortened from /usr/include/linux/input.h).
# 2) a GPIO pin number; when grounded, will simulate corresponding keypress.
# Uses Broadcom pin numbers for GPIO.
# If first element is GND, the corresponding pin (or pins, multiple can be
# given) is a LOW-level output; an extra ground pin for connecting buttons.
# A '#' character indicates a comment to end-of-line.
# File can be edited "live," no need to restart retrogame!

# Here's a pin configuration for the PSPi v2 project:

UP         23  # Up
DOWN       27  # Down
LEFT       22  # Left
RIGHT      17  # Right
Q          19  # Square
ENTER      16  # X
Y          20  # Triangle
ESC        26  # Circle
LEFTCTRL   24  # Left Trigger
RIGHTCTRL  21  # Right Trigger
S          12  # Start
D           6  # Select
VOLUMEDOWN 25  # Volume Down
VOLUMEUP    5  # Volume Up


# For configurations with few buttons (e.g. Cupcade), a key can be followed
# by multiple pin numbers.  When those pins are all held for a few seconds,
# this will generate the corresponding keypress (e.g. ESC to exit ROM).
# Only ONE such combo is supported within the file though; later entries
# will override earlier.
```

I checked several post about the subject but I can't make it work, but I could'nt find anything that is appropriate to my project...

When I start the PSP I end up on the shell. From there I just use the Up button to get the last lines. I can enter kodi like that. Once there the buttons aren't working. When I start emulationstation or StartX it's working fine. It looks like the buttons are well "simulated" on those like I would use the keyboard but not in Kodi

Can someone help me to figure out how to get that working in Kodi ?

Thanks all 

**## EDIT :** 

I tried to configure the controller already. I didn't say it but before this I tried a Retropie Image and installed Kodi from there. Same problem, buttons works in Retropie not in Kodi. And when I try to make a new input in the controller the timer just go to 0 and I can't put any key, like the buttons are not recognize.

I checked the link with the Keymap already but as I'm running the stuff on a PSP which structure should I take ? Remote ? Gamepad ? Keyboard ?
Custom Joystick and I put retrogame like that ?

```
<joystick name="retrogame">
  <button id="27">Down</button>
</joystick>
```

A other thing. The joystick from the PSP is connected to the Gamepad so basically the input from the gamepad are the same for the joystick it's exactly the same wiring.

So I tried like that, I created a new file psp.xml that I put here : ~/.kodi/userdata/keymaps

I wrote this inside :

```
<keymap>
  <global>
    <joystick name="retrogame">
    <button id="27">Down</button>
    <button id="23">Up</button>
    </joystick>
  </global>
</keymap>
```

It is not working either.
Is there any manipulation to do to "activate" the .xml file maybe so that Kodi recognize it ? Should I use a different structure ?

**Comment by PaintYourDragon** [comment]
Unfortunately retrogame is not compatible with Kodi and there is no fix other than connecting a USB keyboard when using the latter.

retrogame generates virtual keypresses via the Linux uinput module. I have no idea why Kodi (vs everything else we've thrown at it) doesn't pick up on these. I've taken a cursory look through the Kodi source and can't find an explanation. But it's a large and unfamiliar codebase. Maybe someone closer to the project has a better understanding what's going on inside there, and how retrogame might generate compatible keypress events.

But otherwise, USB keyboard.
