### ISSUE TITLE
Downloading and Installing retrogame fails on pigrrl zero

### ISSUE THREAD

**Issue by Artillect** [adafruit/Adafruit-Retrogame#46]
```
Downloading, installing retrogame...ERROR
Downloading, installing retrogame.cfg...ERROR
Performing other system configuration...OK
```

I get this when I try to install retrogame on my pigrrl zero.  /boot/retrogame.cfg does not exist, and I've had some trouble remaining connected to the pi via SSH. Any tips as to what I should do to solve this?

**Comment by PaintYourDragon** [comment]
Please use the forums at https://forums.adafruit.com for technical support questions.
