### ISSUE TITLE
GPIO onb PI3a+

### ISSUE THREAD

**Issue by jamhamster** [adafruit/Adafruit-Retrogame#56]

**Comment by jamhamster** [comment]
Retrrogame does not work as expected on a Pi3a+. After some issues, I created a Retrogame.cfg with all of the GPIO mapped to keys and the only available GPIO Pins that work are the lower ones. In a Pi3b+ They all register but in a Pi3a+, only GPIO 7 8 2 5 and 6 work.

**Comment by jamhamster** [comment]
I have tested this thoroughly at the weekend and it is working beautifully, many thanks for this, you saved my build :-)

**Comment by HoolyHoo** [comment]
Still having issues on pi3a+ with GPIO 19 and 20.  I properly assigned them in retrogame.cfg, however, keyboard presses are not showing for those pins.  All others seem fine.
