### ISSUE TITLE
Buttons "misconfigured" in game

### ISSUE THREAD

**Issue by phrankme** [adafruit/Adafruit-Retrogame#61]
Retrogame does not work as expected on a Pi3b. In EmulationStation everything is configured and fine. I also can press "Start" while being in games. But:
Buttons A and B don't work while in game. If I want to use these, I have to press X and Y. How do I configure it right?

Here is my retrograme.cfg that perfectly work in ES but not in game:
```
LEFT      14  # Joypad left
RIGHT     22  # Joypad right
UP         4  # Joypad up
DOWN       5  # Joypad down
LEFTCTRL  21  # 'A' button
LEFTALT   16  # 'B' button
Z         26  # 'X' button
X         20  # 'Y' button
SPACE     18  # 'Select' button
ENTER     13  # 'Start' button
A         12  # Left shoulder button
S          6  # Right shoulder button
```

If I change the configuration in retrogame.cfg like this it works in game, but the buttons in ES now are wrong.
```
LEFT      14  # Joypad left
RIGHT     22  # Joypad right
UP         4  # Joypad up
DOWN       5  # Joypad down
LEFTCTRL  12  # 'A' button > new X (in game)
LEFTALT    6  # 'B' button > new Y (in game)
Z         16  # 'X' button > new A (in game)
X         21  # 'Y' button > new B (in game)
SPACE     18  # 'Select' button
ENTER     13  # 'Start' button
A         26  # Left shoulder button
S         20  # Right shoulder button
```
I'd really appreciate some help. System is recalbox.

**Comment by PaintYourDragon** [comment]
Recalbox has its own methodology for interfacing GPIO controls; you shouldn't need to run retrogame on the system. Some docs here:
https://github.com/recalbox/recalbox-os/wiki/GPIO-controllers-%28EN%29

If you do still decide to use retrogame for some reason, the issue isn't there, it's that EmulationStation and the individual emulator(s) have their controller configurations in different files; EmulationStation's settings aren't being picked up globally. Don't know where to find each emulator's config, you'll have to scrounge around, the wiki above might be some help.
